# Deep Learning Tutorials

a set of tutorials to get myself familiarized with the Pytorch modules

In [1]:
import torch

#### PyTorch 101 - Basics

In [3]:
x = torch.empty(2,5)

In [4]:
x.size()

torch.Size([2, 5])

In [5]:
x.fill_(1.125)  # underscores are present when filling in tensors

tensor([[1.1250, 1.1250, 1.1250, 1.1250, 1.1250],
        [1.1250, 1.1250, 1.1250, 1.1250, 1.1250]])

In [6]:
x.mean()

tensor(1.1250)

In [7]:
x.std()

tensor(0.)

In [8]:
x.sum()

tensor(11.2500)

In [9]:
# extract float number from tensor data object
x.sum().item()

11.25

#### Component Wise & Matrix/vector Operations

In [10]:
x = torch.tensor([10.,20.,30.])
y = torch.tensor([11.,21.,31.])

In [11]:
# sum of vectors
x+y

tensor([21., 41., 61.])

In [12]:
# component wide product 
x*y

tensor([110., 420., 930.])

In [13]:
# component wide exponenets
x**2

tensor([100., 400., 900.])

In [15]:
# high dimensional tensor has weird syntax. pay attention
m = torch.tensor([[0.,0.,3.],
                 [0.,2.,0.],
                 [1.,0.,0.]]
    )

In [16]:
# matrix vector product
m.mv(x)

tensor([90., 40., 10.])

In [17]:
# matrix vector product
m @ x

tensor([90., 40., 10.])

#### Slicing values

In [18]:
x = torch.empty(2,4).random_(10)

In [19]:
x

tensor([[2., 1., 8., 3.],
        [6., 3., 6., 2.]])

In [20]:
# slicing rows
x[0]

tensor([2., 1., 8., 3.])

In [21]:
# same thing
x[0,:]

tensor([2., 1., 8., 3.])

In [22]:
# slicing columns
x[:,0]

tensor([2., 6.])

In [23]:
# setting values on a slice
x[:,1:3] = -1
x

tensor([[ 2., -1., -1.,  3.],
        [ 6., -1., -1.,  2.]])

#### PyTorch provides interface to standard linear operation, such as linear systems, solving or Eigen-decomposition

In [47]:
A = torch.tensor([[[10, 2, 3], [3, 10, 5], [5, 6, 12]]], dtype=torch.float) # shape (1, 3, 3)

In [48]:
B = torch.tensor([[[2, 5, 1], [3, 2, 1], [5, 1, 9]],
                      [[4, 2, 9], [2, 0, 3], [2, 5, 3]]], dtype=torch.float) # shape (2, 3, 3)

In [49]:
X = torch.linalg.lstsq(A, B).solution # A is broadcasted to shape (2, 3, 3)

In [52]:
 torch.dist(X, torch.linalg.pinv(A) @ B)

tensor(3.0468e-07)

#### Linear Regression in PyTorch

In [ ]:
# don't have data file. Wont run properly
import torch, numpy

data = torch.tensor(numpy.loadtxt('systolic-blood-pressure-vs-age.dat'))
nb_samples = data.size(0)

x, y = torch.empty(nb_samples,2), torch.empty(nb_samples,1)

x[:,0] = data[:, 0]
x[:,1] = 1

y[:,0] = data[:, 1]

alpha = torch.linalg.lstsq(y,x)

a,b = alpha[0,0].item(), alpha[0,1].item()


#### Helpful commands
![a](./images/pytorch-command.jpg)
![b](./images/more-commands.jpg)

#### PyTorch offers simple interfaces to standard image databases

In [ ]:
# wont work since I dont have data set
import torch, torchvision
cifar = torchvision.datasets.CIFAR10('./cifar10', train=True, download=True)
x=torch.from_numpy(cifar.data).permute(0,3,1,2).float() / 255
print(x.dtype, x.size(), x.min().item(), x.max().item())

#### Output:

```
Files already downloaded and verified
torch.float32, torch.Size([50000,3,32,32]) 0.0 1.0
```

how to read above output

- 50000 sequence images
- 3 channels
- 32 columns
- 32 rows
- 0.0 min value
- 1.0 max value

#### Other helpful torchvision operators

In [ ]:
# narrows to the first images, converts to float
x = x[:48]

# how to save images
torchvision.utils.save_image(x, 'cifar-4x12.png', nrow=12, pad_value=10)

# switches the rows and column indices
x.transpose_(2,3)

# kills the green and blue channels 
x[:, 1:3].fill_(0)


# Broadcasting and Einstein Summations

**Broadcasting** automagically expands dimensions by replicating coefficients when it is necessary to perform operations that are intuitively reasonable

Precisely broadcasting proceeds as follows:

- if one of the tensors has fewer dimensions than the other, it is reshaped by adding as many dimensions of size 1 as necessary in the front
- for every dimension mismatch, **if one of the two tensors is of size one** it is expanded along this axis by replicating coefficients

if there is a tensor size mismathc for one of the dimension and neither of them is one, the operation fails

Refer to the example below

![c](./images/broadcasting.png)

#### Einstein Broadcasting

A powerful generic tool for complex tensorial operations is the **Einstein summation convention**. It provides a concise way of describing dimension re-ordering and summing of component wise products along some of them

```torch.einsum``` takes as argument a string describing the operation, the tensors to operate on and returns a tensor.

The operation string is a comma-seperated list of indexing followed by the indexing for the result

**Summations are executed on all indexes not appearing in the result indexing**

Examples:

![ein1](./images/ein1.png)
![ein2](./images/ein2.png)